### login
POST https://htmgxlltejrgppquqwbn.supabase.co/functions/v1/users-login
Content-Type: application/json

{
  "email": "terminostermions@gmail.com",
  "password": "Gamecrew1!",
}


### get tutors
POST https://htmgxlltejrgppquqwbn.supabase.co/functions/v1/live-chat-room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Ikphbkw3bVl2bEx2NmVZQisiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2h0bWd4bGx0ZWpyZ3BwcXVxd2JuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhYjczYzNhYS05ODdiLTQzY2UtOTRiMy0zNDFlODhhMDYwNDIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1MzE3MDgzLCJpYXQiOjE3NjUzMTM0ODMsImVtYWlsIjoidGVybWlub3N0ZXJtaW9uc0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcm9maWxlX2lkIjoxNn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjUzMTM0ODN9XSwic2Vzc2lvbl9pZCI6IjI0Yzk4OWNiLTdkZmItNDdmNy1hMjBhLWQwNjIzNDU0NWJkNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.3Vwc64HE0GFrsGmGAoCXax5M_9j9OhEu0PdEXdqFx54
Content-Type: application/json

{
  "tutorId": 2,
  "name": "Sala criado pelo ADM",
  "startAt": "2025-12-09T17:50:00",
  "endAt": "2025-12-09T23:50:00",
  "topics": ["outros"],
}

### get users
GET https://htmgxlltejrgppquqwbn.supabase.co/functions/v1/users-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Ikphbkw3bVl2bEx2NmVZQisiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2h0bWd4bGx0ZWpyZ3BwcXVxd2JuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhYjczYzNhYS05ODdiLTQzY2UtOTRiMy0zNDFlODhhMDYwNDIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1MzQ1OTgxLCJpYXQiOjE3NjUzNDIzODEsImVtYWlsIjoidGVybWlub3N0ZXJtaW9uc0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcm9maWxlX2lkIjoxNn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjUzNDIzODF9XSwic2Vzc2lvbl9pZCI6Ijc2NDk3OWQxLTc5NWUtNDFmNi1hOTExLTI2OWRhYjk3OTI2ZCIsImlzX2Fub255bW91cyI6ZmFsc2V9.mGZ3N4vLw288Dxww5jybc7Cmx-hLildwEolZ8-W0gUI
Content-Type: application/json